---

- name: Apache and Python WSGI will be present.
  apt: name={{ item }} state=present
  with_items: [apache2, libapache2-mod-wsgi]
  become: yes
  become_method: sudo

- name: VirtualHost will be configured.
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf
  become: yes
  become_method: sudo